name: Selenium Python CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 3 * * *'

jobs:
  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest -v --alluredir=Reports

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Logs
          path: logs/
          if-no-files-found: ignore

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AllureResults
          path: Reports/
          if-no-files-found: ignore